#!/bin/bash
# vim:sw=4:ts=4:et
set -e
ME=30-create-user-and-group
PROXY_USER="${PROXY_USER:-toor}"
PROXY_USER_HOME="/tmp/${PROXY_USER}"

entrypoint_log() {
	if [ -z "${ENTRYPOINT_QUIET_LOGS:-}" ]; then
		echo "$ME: $@"
	fi
}

entrypoint_log "INFO: Creating \"${PROXY_USER}\" user/group..."
addgroup ${PROXY_USER}
adduser --ingroup ${PROXY_USER} --shell /bin/false --no-create-home --gecos ${PROXY_USER} --disabled-password ${PROXY_USER}
usermod -p '*' ${PROXY_USER}

exit 0
