services:
  server:
    image: chocolatefrappe/ssh-proxy-server:local
    environment:
      - AUTHORIZED_KEYS_FILE=${AUTHORIZED_KEYS_FILE:-/run/secrets/authorized_keys}
    secrets:
      - source: authorized_keys
        mode: 0700
    volumes:
      - server_data:/data
    ports:
      - mode: host
        target: 22
        published: 2222
        protocol: tcp
      - mode: host
        target: 22
        published: 2222
        protocol: udp
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
secrets:
  authorized_keys:
    file: authorized_keys
volumes:
  server_data:
