services:
  server:
    image: chocolatefrappe/ssh-proxy-server:local
    environment:
      - AUTHORIZED_KEYS_FILE=${AUTHORIZED_KEYS_FILE:-/run/secrets/authorized_keys}
    secrets:
      - source: ssh-forward-client.pub
        target: /authorized_keys.d/ssh-forward-client.pub
        mode: 0700
    volumes:
      - server_data:/data
    ports:
      - mode: host
        target: 22
        published: 2222
        protocol: tcp
      - mode: host
        target: 22
        published: 2222
        protocol: udp
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
      restart_policy:
        delay: 15s
        window: 120s
secrets:
  ssh-forward-client.pub:
    file: ssh-forward-client.pub
volumes:
  server_data:
