#!/bin/bash
# vim:sw=4:ts=4:et
set -e
ME=30-authorized-keys
PROXY_USER="${PROXY_USER:-toor}"
PROXY_USER_HOME="/tmp/${PROXY_USER}"
PROXY_USER_SSH_DIR="${PROXY_USER_HOME}/.ssh"
AUTHORIZED_KEYS_FILE="${AUTHORIZED_KEYS_FILE:-/run/secrets/authorized_keys}"

entrypoint_log() {
	if [ -z "${ENTRYPOINT_QUIET_LOGS:-}" ]; then
		echo "$ME: $@"
	fi
}

function import_authorized_keys() {
	local in_dir="$1"
	local out_file="$2"

	# Create the authorized_keys file if it does not exist
	if [ ! -f "${out_file}" ]; then
		mkdir -p "$(dirname ${out_file})"
		touch "${out_file}"
	fi

	# Iterate over all files in the /authorized_keys.d directory
	for file in ${in_dir}/*.pub; do
		if [ -f "${file}" ]; then
			# verify that the file is a valid ssh public key
			entrypoint_log "INFO: Verifying public key: \"${file}\""
			if ssh-keygen -lf "${file}"; then
				# Concatenate the file to the authorized_keys file
				cat "${file}" >> ${out_file}
				entrypoint_log "INFO: Authorized key: \"${file}\""
			else
				entrypoint_log "ERROR: \"${file}\" is not a valid ssh public key"
				continue
			fi

		fi
	done
}

entrypoint_log "INFO: Import authorized keys from \"/authorized_keys.d\" directory..."
import_authorized_keys "/authorized_keys.d" "/etc/ssh/authorized_keys"

entrypoint_log "INFO: Set up monitoring on \"/authorized_keys.d\" directory..."
inotifywait --quiet -r -m -e create,delete "/authorized_keys.d" |
	while read directory event filename; do
		# entrypoint_log "DEBUG: directory: ${directory}, event: ${event}, filename: ${filename}"
		entrypoint_log "INFO: Detected change in \"/authorized_keys.d\" directory..."

		# Refresh authorized keys from /authorized_keys.d directory
		import_authorized_keys "/authorized_keys.d" "/etc/ssh/authorized_keys2"
		# Remove previous authorized_keys file and rename authorized_keys2 to authorized_keys
		rm "/etc/ssh/authorized_keys"
		mv "/etc/ssh/authorized_keys2" "/etc/ssh/authorized_keys"

		# If a DELETE event was detected, restart sshd
		if [ "$event" == "DELETE" ]; then
			killall sshd # Drop all ssh connections and restart sshd
			s6-svc -r /run/service/sshd
		fi
	done
