#!/bin/bash
# vim:sw=4:ts=4:et

set -e

ME=knockd

entrypoint_log() {
	if [ -z "${ENTRYPOINT_QUIET_LOGS:-}" ]; then
		echo "$@"
	fi
}

entrypoint_log "INFO: Starting $ME..."
/usr/sbin/knockd --verbose | while read -r line; do
	entrypoint_log "INFO: $ME: $line"
done
